name: .NET

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build in Debug mode
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --filter FullyQualifiedName!~Hw13Tests --no-build --verbosity normal --collect:"XPlat Code Coverage" --settings .github/coverlet.runsettings
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build in Debug mode
        run: dotnet build
      - name: test
        run: dotnet test --filter FullyQualifiedName\!~Hw13Tests --logger "trx;LogFileName=test-results.trx" --no-build
      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: HomeWork*/Hw*Tests/TestResults/*.trx
